name: Trigger auto deployment for api-gateway

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ development ]
    paths:
    - '**'
    - '.github/workflows/api-gateway-AutoDeployTrigger-31a81b6a-373c-4aa7-b0dd-e7f87c440f71.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APIGATEWAY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APIGATEWAY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APIGATEWAY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/apps/api-gateway
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.APIGATEWAY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APIGATEWAY_REGISTRY_PASSWORD }}
          containerAppName: api-gateway
          resourceGroup: CodeBlue
          imageToBuild: youssefhassanien1/api-gateway:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


