name: Trigger auto deployment for auth-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      [
        'apps/auth/**',
        '.github/workflows/auth-service.yml',
        'package.json',
        package-lock.json,
      ]

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v6.0.1

      - name: Azure Login
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AUTHSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AUTHSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AUTHSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: apps/auth/Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.AUTHSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AUTHSERVICE_REGISTRY_PASSWORD }}
          containerAppName: auth-service
          resourceGroup: Graduation-Project
          imageToBuild: youssefhassanien1/auth-service:${{ github.sha }}
