name: Deploy to EC2

on:
  push:
    branches: [development]
    paths:
      [
        'apps/auth/**',
        'apps/doctor/**',
        'apps/api-gateway/**',
        '.github/workflows/aws.yml',
        'package.json',
        'package-lock.json',
      ]
  workflow_dispatch:

jobs:
  # JOB 1: BUILD AND PUSH IMAGES
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Auth Service
      - name: Build and Push Auth
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/auth/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      # Build and Push API Gateway
      - name: Build and Push API Gateway
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/api-gateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

      # Build and Push Doctor Service
      - name: Build and Push Doctor
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/doctor/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/doctor-service:latest

  # JOB 2: DEPLOY TO EC2
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to project folder
            cd ~/CodeBlue
            
            # Stop the old containers
            docker compose down
            
            # Pull the new images we just pushed
            docker compose pull
            
            # Start everything up again
            docker compose up -d
            
            # Remove unused images to save disk space
            docker image prune -f
