name: doctor-service auto deployment trigger

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ development ]
    paths:
      [
          'apps/doctor/**',
          '.github/workflows/doctor-service.yml',
          'package.json',
          'package-lock.json',
      ]

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v6.0.1

      - name: Azure Login
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets.DOCTORSERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DOCTORSERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DOCTORSERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: apps/doctor/Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.DOCTORSERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DOCTORSERVICE_REGISTRY_PASSWORD }}
          containerAppName: doctor-service
          resourceGroup: CodeBlue
          imageToBuild: youssefhassanien1/doctor-service:${{ github.sha }}


